version: "3.2"


services:
  django_app:
    container_name: 'django'
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0:8000
    volumes:
      - ./:/app
    ports:
      - 80:8000
    image: app-image
    networks:
      - main

  celery_app:
    container_name: 'celery'
    image: app-image
    working_dir: /app/task_list
    command: celery -A celery worker -l INFO
    depends_on: 
    - rabbitmq
    - django_app
    networks:
      - main

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - main
networks: 
  main:
